Modify design to match Subjective iOS, and change disabled action col…
circles-png/SubjectiveAssembly pull request #6
Opened 2023-07-24 08:25 UTC by dcndr

…our from red to grey to reserve red for destructive actions. (lol typo in commit whoops)

2023-07-24 09:16 UTC, circles-png requested changes
53%

contrast is an issue
fails to address mobile users?
lack of padding especially on header
colour choices _subjectively_ bad
dividers are completely gone
colour scheme weird

9/10 dentists would not recommend this

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Bell/index.tsx
> +    <span>Bell {number}</span>
again, capitals

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Bell/index.tsx
> +    'text-black bg-gold-200 rounded-md transition duration-300 text-center flex justify-between p-2 sm:px-4',
cinder 950 is basically black but better

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/DayButtons/index.tsx
> +        'rounded-xl w-10 md:w-screen p-2 mr-4 h-30 flex justify-center items-center border-none transition duration-300 hover:scale-[1.1] text-black shadow-gold-200/10',
`border-none` is default so just remove it

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/DayButtons/index.tsx
> +        'rounded-xl w-10 md:w-screen p-2 mr-4 h-30 flex justify-center items-center border-none transition duration-300 hover:scale-[1.1] text-black shadow-gold-200/10',
w-screen is bad

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Divider/index.tsx
> +const Divider = () => <div className='h-[2px] bg-black-500 rounded-full shrink-0 grow-0 basis-[2px] shadow shadow-gold-200/20' />
there are no shades of black; black-500 does nothing, you should know this from webstorm's tailwindcss integration

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Header/index.tsx
> +const Header = () => <header className='text-left justify-center'>
text-left is default, remove it

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Header/index.tsx
> +      <span className='text-gold-300'>&nbsp;Assembly</span>
why nbsp tho
just use `gap`

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Header/index.tsx
> +    <div className = 'text-4xl'>
formatting, `=` should not be surrounded by spaces here

2023-07-24 09:16 UTC, circles-png commented on frontend/src/components/Header/index.tsx
> +      <span className='text-gold-300'>&nbsp;Assembly</span>
the two spans can also be merged, contrast is negligible

2023-07-24 09:16 UTC, circles-png commented on frontend/tailwind.config.cjs
the colours were generated at https://uicolors.app so that they would work as well as possible

are these colours hand picked?

2023-07-24 09:24 UTC, circles-png commented
![image](https://github.com/circles-png/SubjectiveAssembly/assets/27723996/2e05e9e0-dd21-4531-b00a-2b4458d97446)

2023-07-24 09:30 UTC, dcndr commented
lmao ‘twas a rush job. shall fix contrast and other stuff

2023-07-24 11:16 UTC, dcndr commented on frontend/src/App.tsx
> -          DAYS
too big for all caps imo

2023-07-24 13:39 UTC, dcndr commented
I think I fixed most stuff idk

2023-07-25 06:35 UTC, circles-png commented
ask people what they think

2023-07-30 10:36 UTC, circles-png commented
- contrast issues
    - cursor (consider removing this, ask people what they think)
    - disabled bell button bg colour is `bg-gray-100` on `bg-gray-50`

2023-08-07 04:37 UTC, circles-png commented
closed until figma done

2023-08-07 04:37 UTC, closed without merging